[package]
name = "ctc"
version = "0.2.2"
edition = "2021"
homepage = "https://github.com/sahandevs/ctc"
description = "load config files on compile time."
license = "MIT"
readme = "../README.md"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0"
toml = "0.4"
serde = "1.0"
